### ISSUE TITLE
[!] Fehlernder Current Buyer

### ISSUE THREAD

**Issue by Nedomil** [scg-unibe-ch/ese2016-team1#11]
**Problemstellung**
_Current Buyer_ ist nicht (mehr) implementiert.

**Codeausschnitt aus _makeAuction.jsp_ ab Zeile 144**

		<table class="placeAdTable">
			<tr>
				<td><h2>Current Buyer</h2></td>
			</tr>	
				
			<tr>	
				<td><h2>Current Bidding</h2></td>
				<td>
				<form:input id="currentBidding" type="number" path="currentBidding"
						placeholder="Current Bidding" step="50" value="${ad.currentBidding }"/> <form:errors
						path="currentBidding" cssClass="validationErrorText"/>
				</td>
			</tr>

**Comment by GretarGeiser** [comment]
de current Buyer set öbernoh wärde sobaud öper bietet oder ufchouft
