### ISSUE TITLE
Details zu Auktionen

### ISSUE THREAD

**Issue by janikEndtner** [scg-unibe-ch/ese2016-team1#19]
- Wenn die Auktion geschlossen wurde, muss angemerkt werden warum dies so ist (Auktionsende erreicht, Sofort kaufen)

**Comment by Nedomil** [comment]
@janikEndtner 
Ist davon etwas bereits getan worden oder soll man das noch als drei neue Issues deklarieren?

**Comment by janikEndtner** [comment]
Issue angepasst. Rest ist erledigt
