### ISSUE TITLE
Frage: Abgelaufene Auktionen in Suche (Beantwortet: jetzt "to do")

### ISSUE THREAD

**Issue by Nedomil** [scg-unibe-ch/ese2016-team1#25]
**Frage**
Werden abgelaufene Auktionen in der Suchfunktion bereits gefiltert und dementsprechend nicht angezeigt? (Sowohl bei zeitlich abgelaufenen, wie auch bei per Sofortkauf gewonnene).

**Problemstellung**
Abgelaufene Autktionen werden von der Suchfunktion noch gefunden. Sollte noch unterbunden werden. Wichtig dabei ist, dass sowohl zeitlich abgelaufene, wie auch sofort gekaufte nicht mehr angezeigt werden.

**Comment by janikEndtner** [comment]
Muss noch erledigt werden!

**Comment by janikEndtner** [comment]
Erledigt. Unter "newest adds" erscheinen sie noch. Soll aber so sein
