### ISSUE TITLE
Auktionen-System

### ISSUE THREAD

**Issue by Nedomil** [scg-unibe-ch/ese2016-team1#3]
!!!! Wird in weiteren Issues aufgesplittet und dient lediglich noch der Gesamtübersicht !!!!

**Layout**
Darstellung von _adDescription.jsp_:
![auktion](https://cloud.githubusercontent.com/assets/22456707/19779348/010ded58-9c81-11e6-8338-918862777693.png)

Darstellung von _placeAd.jsp_:
Für das erstellen einer Auktion sollten folgende Informationen notwendig sein:
- Mindestpreis
- Auktionsende (Datum)
- Sofortkauf (ein oder aus)
- Sofortkaufpreis (falls ein)

Optional: Auswahl bereits so gestaltet, dass man entweder Miete, Verkauf oder Auktionshaus wählen kann. (Momentan noch alles gleichzeitig. Kann auch zu einem späteren Zeitpunkt gemacht werden).

**Funktionalität**
Jeder Benutzer soll mittels _Menü->Place an ad_ eine Auktion eröffnen (und bearbeiten!) können. Andere User sollen darauf bieten können. Bieten erfolgt mit einem fixen Betrag, der _105%_ des vorherigen Gebotes entspricht. Wird ein Gebot 15 Minuten vor Ablauf der Auktion getätigt, verschiebt sich das Auktionsende um 15 Minuten. Optional soll es möglich sein, als "Ad-Placer" einen Sofortkaufpreis festzulegen. Nach Auktionsende oder Sofortkauf, soll die Auktion nicht mehr aktiv sein (also soll nicht mehr geboten/gekauft werden können).

**Comment by GretarGeiser** [comment]
d auktion set fonktioniere mer cha ou d buyout fontion awände
de current buyer nehmts ah ond es werd ou es mail a bieter ond vorhärig current buyer gscheckt

allerdengs werds änddatum noni noch hendere gschobe
s ganze gseht ou noni so schön us, bzw es werd ou noni alles so wie bim böud azeigt
