### ISSUE TITLE
Erhöhungsschritt bei der Auktion hängt vom aktuellen Gebot ab

### ISSUE THREAD

**Issue by Maxasi** [scg-unibe-ch/ese2016-team1#32]
Momentan hängt der Erhöhungsschritt bei der Auktion vom aktuellen Gebot ab. Es würde mehr Sinn ergeben, den Erhöhungsschritt abhängig vom Startpreis zu machen (sonst gilt: je höher der Preis, desto höher der Erhöhungsschritt).

**Comment by Nedomil** [comment]
Isch Wunsch vom Chund.
