### ISSUE TITLE
Karte in AdDescription

### ISSUE THREAD

**Issue by Nedomil** [scg-unibe-ch/ese2016-team1#49]
**Problemstellung**
In _AdDescription_ soll automatisch eine Karte (z.B. _GoogleMaps_) generiert werden, auf der die genaue Position des "Ad-Objektes" dargestellt wird. Die Karte soll dabei interaktiv sein. Man soll also zoomen und sie bewegen können.

**Comment by janikEndtner** [comment]
Zentrum von Stadt in der das Ad-Objekt liegt wurde gewählt. Muss mit Manuel abgeklärt werden.
