### ISSUE TITLE
Funktionieren die Mails in MakeAuctionController alle?

### ISSUE THREAD

**Issue by Nedomil** [scg-unibe-ch/ese2016-team1#67]
**Frage (@GretarGeiser @janikEndtner)**
Ab Zeile 187 steht dieser Code. Der kann doch nicht funktionieren? `ad.getCurrentBuxer()` ist doch ein Name und keine Email-Adresse? Oder wird dort die Adresse abgespeichert? Wenn ja. Wieso ist currentBuyer nicht vom Typ _User_? Währe nämlich unbedingt nötig.

**Code**
`MailService mail = new MailService();
				if (price >= ad.getRetailPrice()) {
					mail.sendEmail(ad.getCurrentBuyer(),5,"http://localhost:8080/ad?id="+id);
					message2.setText("We are sorry to anounce, someone just bought out the Auction you were leading: <a href=\"http://localhost:8080/ad?id="+id + "\">"+ ad.getTitle() + ".</a> ");

				}
				else{
					mail.sendEmail(ad.getCurrentBuyer(),2,"http://localhost:8080/ad?id="+id);
					message2.setText("Someone just replaced you as current highest Bidder on this Auction: <a href=\"http://localhost:8080/ad?id="+id + "\">"+ ad.getTitle() + ".</a> ");

				}`

**Comment by janikEndtner** [comment]
Keine Ahnung. Habe dort nichts gemacht.
