### ISSUE TITLE
EditAd speichert Bilder ohne das Ad zu speichern

### ISSUE THREAD

**Issue by Nedomil** [scg-unibe-ch/ese2016-team1#68]
**Problemstellung**
Fehler werden zwar jetzt angezeigt. EditAd speichert aber die eingetragenen Werte trotz Fehler.

**Comment by GretarGeiser** [comment]
Probleme nur noch mit Bilder, Visits und Roommates

**Comment by GretarGeiser** [comment]
Gelöst auf branch visits

**Comment by Nedomil** [comment]
Close?
