### ISSUE TITLE
Nachrichtendienst für Auktionen

### ISSUE THREAD

**Issue by Nedomil** [scg-unibe-ch/ese2016-team1#7]
**Problemstellung**
Der Placer soll über die Ereignisse seiner Ad (Bsp. Kauf, Gebot) per Nachricht in Kenntnis gesetzt werden. Bei Auktionen sollen die Bieter darüber informiert werden, wenn sie überboten werden. Zu implementieren sind also die Nachrichten für:
- den "Placer": Erhält Nachricht bei Kauf, Gebot, Kauf und Auktionsende.
- die Bieter: Erhält Nachricht bei Kauf, Überbietung und Auktionsende.

**Comment by GretarGeiser** [comment]
das nochrechte zügs set fonktioniere
vellecht wärs no guet wenn ers ou no wörder usprobiere
