### ISSUE TITLE
Benachrichtigung bei Sieg/Kauf in Auktionen.

### ISSUE THREAD

**Issue by Nedomil** [scg-unibe-ch/ese2016-team1#75]
**Frage**
Sollten wir nicht ursprünglich implementieren, dass der User eine Auktion durch Ablaufen der Zeit (als Höchstbieter) oder durch Sofortkauf eine Wohnung ersteigert, eine Benachrichtigung (mit Link zur _AdDescription_) erhält? Zumindest beim Sofortkauf geschieht das nicht!

**Comment by GretarGeiser** [comment]
Beim Sofortkauf macht es ja keinen Sinn. Der User ist sich ja bewusst, dass er gerade ein Grundstück ersteigert hat.
Aber bei Ablauf der Zeit haben wir meines Wissens bis jetzt nicht derartiges implementiert.

**Comment by Nedomil** [comment]
Joah, wissen tut er es ja schon. Aber wenn er es einmal gekauft hat, hat er keine Möglichkeit mehr, die Description anzusehen. Hat er also den Käufer nicht vorher kontaktiert oder will noch etwas nachsehen, besteht für ihn diese Möglichkeit nicht mehr.
