### ISSUE TITLE
Sell und Auction funkrioniert nicht mehr

### ISSUE THREAD

**Issue by GretarGeiser** [scg-unibe-ch/ese2016-team1#76]
**Problemstellung**
Bei manchen Ads aus den Testdaten ist es nicht möglich, den Verkaufstyp zu ändern. Beispiel dafür ist _Direkt am Quai: hübsches Studio_ vom ESE-Konto. Fehler geschieht in JavaScript.
![image](https://cloud.githubusercontent.com/assets/22456707/21081572/3cffaf7e-bfca-11e6-94ff-11d2d8aac504.png)

**Comment by janikEndtner** [comment]
Konnte das sehr wahrscheinlich lösen. Bitte noch testen!!
novalidate attribute zur editAd Form hinzugefügt, welche unnötig Clientseitige Validation verhindert, welche das Problem auslöste

**Comment by Nedomil** [comment]
Ich habe ein wenig damit gespielt. Bisher scheint es zu funktionieren. Genau dasselbe hatte ich auch versucht, aber mich offensichtlich mit der Syntax vertan :/
